include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
  exclude:
    - lib/**/*.g.dart  
    - lib/**/*.freezed.dart
linter:
  rules:
    public_member_api_docs: false
